version: '3'

services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    ports:
      - 80:3000
    volumes:
      - .:/src
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ieat-data:/var/lib/postgresql/data
volumes:
  ieat-data:
